# Generated by Django 4.2.3 on 2023-07-25 10:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', models.CharField(max_length=250, verbose_name='Yorum')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('post_id', models.IntegerField(default=0)),
                ('show_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('user_id', models.IntegerField(default=0, editable=False)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('view_counter', models.IntegerField(default=0, editable=False)),
                ('category_slug', models.CharField(max_length=150, verbose_name='Kategori Slug')),
                ('show_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
