# Generated by Django 4.2.3 on 2023-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_haber_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='show_status',
            field=models.BooleanField(default=True),
        ),
    ]
